/*
 * PAUL Open Human Evaluation — Google Forms sandbox runtime.
 *
 * This script consumes PAUL_HUMAN_EVAL_SPEC generated by
 * scripts/build_google_forms_sandbox.py. It creates short, anonymous Google
 * Forms, links a response spreadsheet, normalizes submissions, and can close a
 * sandbox form after a configured test count. It never receives model/source
 * identities or the H1 private A/B mapping.
 */

const PAUL_FORM_PROPERTY_PREFIX = 'PAUL_HUMAN_EVAL_FORM_';
const PAUL_NORMALIZED_SHEET = 'PAUL Normalized';
const PAUL_METADATA_SHEET = 'PAUL Metadata';

function createPaulHumanEvalSandboxForms() {
  if (typeof PAUL_HUMAN_EVAL_SPEC === 'undefined') {
    throw new Error('PAUL_HUMAN_EVAL_SPEC is missing. Add the generated Payload.gs file.');
  }
  const packets = PAUL_HUMAN_EVAL_SPEC.packets;
  if (!Array.isArray(packets) || packets.length === 0) {
    throw new Error('PAUL_HUMAN_EVAL_SPEC.packets must be a non-empty array.');
  }

  const created = packets.map((packet) => createPaulHumanEvalForm_(packet));
  console.log(JSON.stringify(created, null, 2));
  return created;
}

function createPaulHumanEvalForm_(packet) {
  validatePacket_(packet);

  // Create unpublished so no respondent can enter while items/settings are incomplete.
  const form = FormApp.create(packet.title, false);
  form
      .setDescription(packet.description)
      .setCollectEmail(false)
      .setAllowResponseEdits(false)
      .setLimitOneResponsePerUser(false)
      .setProgressBar(true)
      .setPublishingSummary(false)
      .setShowLinkToRespondAgain(false)
      .setShuffleQuestions(false)
      .setConfirmationMessage(packet.confirmation_message)
      .setAcceptingResponses(false);

  const spreadsheet = SpreadsheetApp.create(
      `PAUL Human Eval — ${packet.packet_id} — Responses`,
  );
  const metadataSheet = spreadsheet.getSheets()[0];
  metadataSheet.setName(PAUL_METADATA_SHEET);
  const normalizedSheet = spreadsheet.insertSheet(PAUL_NORMALIZED_SHEET);
  normalizedSheet.appendRow([
    'response_id',
    'submitted_at_utc',
    'packet_id',
    'batch_id',
    'variant_id',
    'reviewer_cohort',
    'language',
    'comparison_id',
    'choice',
    'optional_comment',
  ]);

  const choiceItemToComparison = {};
  for (const comparison of packet.comparisons) {
    form.addSectionHeaderItem()
        .setTitle(comparison.display_title)
        .setHelpText(comparisonHelpText_(comparison));

    const choiceItem = form.addMultipleChoiceItem()
        .setTitle(comparison.question)
        .setChoiceValues(comparison.choices)
        .setRequired(true);
    choiceItemToComparison[String(choiceItem.getId())] = comparison.comparison_id;
  }

  let optionalCommentItemId = null;
  if (packet.optional_comment && packet.optional_comment.enabled) {
    const commentItem = form.addParagraphTextItem()
        .setTitle(packet.optional_comment.title)
        .setRequired(false);
    optionalCommentItemId = String(commentItem.getId());
  }

  form.setDestination(FormApp.DestinationType.SPREADSHEET, spreadsheet.getId());

  const runtimeConfig = {
    environment: packet.environment,
    packet_id: packet.packet_id,
    batch_id: packet.batch_id,
    variant_id: packet.variant_id,
    reviewer_cohort: packet.reviewer_cohort,
    language: packet.language,
    spreadsheet_id: spreadsheet.getId(),
    choice_item_to_comparison: choiceItemToComparison,
    optional_comment_item_id: optionalCommentItemId,
    sandbox_auto_close_after_submissions: packet.sandbox_auto_close_after_submissions,
  };
  PropertiesService.getScriptProperties().setProperty(
      PAUL_FORM_PROPERTY_PREFIX + form.getId(),
      JSON.stringify(runtimeConfig),
  );

  writeMetadataSheet_(metadataSheet, form, packet, choiceItemToComparison);
  ScriptApp.newTrigger('onPaulHumanEvalSubmit').forForm(form).onFormSubmit().create();

  // Publish only after the complete form, response destination and trigger exist.
  form.setPublished(true).setAcceptingResponses(true);

  return {
    packet_id: packet.packet_id,
    form_id: form.getId(),
    respondent_url: form.getPublishedUrl(),
    editor_url: form.getEditUrl(),
    spreadsheet_id: spreadsheet.getId(),
    spreadsheet_url: spreadsheet.getUrl(),
  };
}

function comparisonHelpText_(comparison) {
  return [
    'Question',
    comparison.prompt,
    '',
    'Response A',
    comparison.response_a,
    '',
    'Response B',
    comparison.response_b,
  ].join('\n');
}

function writeMetadataSheet_(sheet, form, packet, itemMap) {
  const rows = [
    ['field', 'value'],
    ['packet_id', packet.packet_id],
    ['batch_id', packet.batch_id],
    ['variant_id', packet.variant_id],
    ['environment', packet.environment],
    ['reviewer_cohort', packet.reviewer_cohort],
    ['language', packet.language],
    ['form_id', form.getId()],
    ['form_packet_version', packet.form_packet_version],
    ['protocol_version', packet.protocol_version],
    ['', ''],
    ['choice_item_id', 'comparison_id'],
  ];
  for (const itemId of Object.keys(itemMap).sort()) {
    rows.push([itemId, itemMap[itemId]]);
  }
  sheet.getRange(1, 1, rows.length, 2).setValues(rows);
  sheet.setFrozenRows(1);
}

function onPaulHumanEvalSubmit(event) {
  if (!event || !event.source || !event.response) {
    throw new Error('This function must run from a Google Forms submit trigger.');
  }
  const form = event.source;
  const propertyKey = PAUL_FORM_PROPERTY_PREFIX + form.getId();
  const encoded = PropertiesService.getScriptProperties().getProperty(propertyKey);
  if (!encoded) {
    throw new Error(`Missing runtime mapping for form ${form.getId()}.`);
  }
  const config = JSON.parse(encoded);
  const spreadsheet = SpreadsheetApp.openById(config.spreadsheet_id);
  const normalized = spreadsheet.getSheetByName(PAUL_NORMALIZED_SHEET);
  if (!normalized) {
    throw new Error(`Missing ${PAUL_NORMALIZED_SHEET} sheet.`);
  }

  const response = event.response;
  const responseId = response.getId();
  if (!responseId) {
    throw new Error('Submitted FormResponse unexpectedly has no response ID.');
  }
  if (normalizedResponseExists_(normalized, responseId)) {
    console.log(`Response ${responseId} is already normalized; skipping duplicate trigger run.`);
    return;
  }

  let optionalComment = '';
  const answersByItem = {};
  for (const itemResponse of response.getItemResponses()) {
    const itemId = String(itemResponse.getItem().getId());
    answersByItem[itemId] = String(itemResponse.getResponse() || '');
    if (itemId === config.optional_comment_item_id) {
      optionalComment = answersByItem[itemId];
    }
  }

  const timestamp = response.getTimestamp();
  const submittedAtUtc = timestamp ? timestamp.toISOString() : new Date().toISOString();
  const rows = [];
  for (const itemId of Object.keys(config.choice_item_to_comparison)) {
    const comparisonId = config.choice_item_to_comparison[itemId];
    const choice = answersByItem[itemId];
    if (!choice) {
      throw new Error(`Required comparison ${comparisonId} has no recorded choice.`);
    }
    rows.push([
      responseId,
      submittedAtUtc,
      config.packet_id,
      config.batch_id,
      config.variant_id,
      config.reviewer_cohort,
      config.language,
      comparisonId,
      choice,
      optionalComment,
    ]);
  }

  if (rows.length > 0) {
    normalized.getRange(normalized.getLastRow() + 1, 1, rows.length, rows[0].length)
        .setValues(rows);
  }

  maybeCloseSandboxForm_(form, config);
}

function normalizedResponseExists_(sheet, responseId) {
  const lastRow = sheet.getLastRow();
  if (lastRow <= 1) {
    return false;
  }
  const responseIds = sheet.getRange(2, 1, lastRow - 1, 1).getValues();
  return responseIds.some((row) => row[0] === responseId);
}

function maybeCloseSandboxForm_(form, config) {
  const target = config.sandbox_auto_close_after_submissions;
  if (config.environment !== 'sandbox' || target === null || target === undefined) {
    return;
  }
  if (!Number.isInteger(target) || target < 1) {
    throw new Error('Invalid sandbox auto-close target in runtime config.');
  }
  if (form.getResponses().length >= target) {
    form
        .setAcceptingResponses(false)
        .setCustomClosedFormMessage(
            'This sandbox form has reached its test response target. Thank you.',
        );
  }
}

function verifyPaulHumanEvalSandboxForms() {
  const properties = PropertiesService.getScriptProperties().getProperties();
  const results = [];
  for (const key of Object.keys(properties).sort()) {
    if (!key.startsWith(PAUL_FORM_PROPERTY_PREFIX)) {
      continue;
    }
    const config = JSON.parse(properties[key]);
    if (config.environment !== 'sandbox') {
      continue;
    }
    const formId = key.slice(PAUL_FORM_PROPERTY_PREFIX.length);
    const form = FormApp.openById(formId);
    const spreadsheet = SpreadsheetApp.openById(config.spreadsheet_id);
    results.push({
      packet_id: config.packet_id,
      form_id: formId,
      published: form.isPublished(),
      accepting_responses: form.isAcceptingResponses(),
      collects_email: form.collectsEmail(),
      allows_response_edits: form.canEditResponse(),
      response_count: form.getResponses().length,
      normalized_rows: Math.max(
          0,
          spreadsheet.getSheetByName(PAUL_NORMALIZED_SHEET).getLastRow() - 1,
      ),
    });
  }
  console.log(JSON.stringify(results, null, 2));
  return results;
}

function closePaulHumanEvalSandboxForms() {
  const properties = PropertiesService.getScriptProperties().getProperties();
  const closed = [];
  for (const key of Object.keys(properties).sort()) {
    if (!key.startsWith(PAUL_FORM_PROPERTY_PREFIX)) {
      continue;
    }
    const config = JSON.parse(properties[key]);
    if (config.environment !== 'sandbox') {
      continue;
    }
    const formId = key.slice(PAUL_FORM_PROPERTY_PREFIX.length);
    const form = FormApp.openById(formId);
    form
        .setAcceptingResponses(false)
        .setCustomClosedFormMessage('This sandbox evaluation is closed. Thank you.');
    closed.push({packet_id: config.packet_id, form_id: formId});
  }
  console.log(JSON.stringify(closed, null, 2));
  return closed;
}

function validatePacket_(packet) {
  if (!packet || packet.environment !== 'sandbox') {
    throw new Error('H2 runtime accepts sandbox packets only.');
  }
  if (!Array.isArray(packet.comparisons) || packet.comparisons.length < 1) {
    throw new Error('Packet must contain at least one comparison.');
  }
  if (packet.comparisons.length > 4) {
    throw new Error('Packet exceeds the four-comparison UX hard cap.');
  }
  if (packet.settings.collect_email !== false ||
      packet.settings.allow_response_edits !== false ||
      packet.settings.limit_one_response_per_user !== false ||
      packet.settings.publish_response_summary !== false ||
      packet.settings.show_submit_another_response_link !== false ||
      packet.settings.shuffle_questions !== false ||
      packet.settings.progress_bar !== true) {
    throw new Error('Packet settings violate the frozen low-friction/blinding protocol.');
  }
  for (const comparison of packet.comparisons) {
    if (!Array.isArray(comparison.choices) || comparison.choices.length !== 5) {
      throw new Error('Each comparison must expose exactly five frozen preference choices.');
    }
    if (comparison.required !== true) {
      throw new Error('Each preference question must be required.');
    }
  }
}
