// PAUL Open H3 durability pilot payload.
// Disposable non-research material only. No benchmark, DHE, SHAE, SFT/DPO identity, or sealed prompt.
//
// Usage: in the already-authorized standalone Apps Script project, use the current repository
// tools/google_forms/Code.gs and this file instead of SandboxPayload.gs, then run
// createPaulHumanEvalSandboxForms(). The two packets auto-close after 3 genuine submissions each.

const PAUL_HUMAN_EVAL_SPEC = {
  packets: [
    {
      form_packet_version: '1.1',
      protocol_version: '1.0',
      environment: 'sandbox',
      packet_id: 'HEF1-H3-A1-20260910',
      batch_id: 'HEB1-H3-UX-20260910',
      variant_id: 'A1',
      partition: 'development',
      reviewer_cohort: 'general_user',
      language: 'en',
      title: 'PAUL Open — H3 Durability Pilot — A1',
      description: 'Disposable non-research H3 pilot. Read each question and the two responses, then choose the response you would rather receive based on accuracy, clarity, usefulness and naturalness.',
      settings: {
        collect_email: false,
        allow_response_edits: false,
        limit_one_response_per_user: false,
        progress_bar: true,
        publish_response_summary: false,
        show_submit_another_response_link: false,
        shuffle_questions: false,
        accepting_responses: true,
      },
      comparisons: [
        {
          ordinal: 1,
          comparison_id: 'H3-DISP-001',
          display_title: 'Comparison 1 of 3',
          prompt: 'Why can a metal spoon feel colder than a wooden spoon even when both have been in the same room?',
          response_a: 'They are usually at nearly the same room temperature. Metal conducts heat away from your hand much faster than wood, so your skin cools more quickly and the metal feels colder.',
          response_b: 'Metal naturally stays at a lower temperature than wood indoors because metal contains less stored heat. That lower temperature is what your hand detects.',
          question: 'Which response would you rather receive?',
          choices: [
            'Response A is better',
            'Response B is better',
            'They are about equally good',
            'Neither response is good',
            "I'm not sure / I can't judge this",
          ],
          required: true,
          domain: 'general_science',
        },
        {
          ordinal: 2,
          comparison_id: 'H3-DISP-002',
          display_title: 'Comparison 2 of 3',
          prompt: 'I have 90 minutes before a quiz. How should I use the time?',
          response_a: 'Spend 10 minutes listing the topics and identifying your weakest two. Use 50 minutes for active recall and practice questions on those areas, 20 minutes to review mistakes, and the final 10 minutes for a quick summary and setup for the quiz.',
          response_b: 'Read the entire textbook chapter from the beginning so nothing is missed. If time remains, highlight the most important pages and reread them once.',
          question: 'Which response would you rather receive?',
          choices: [
            'Response A is better',
            'Response B is better',
            'They are about equally good',
            'Neither response is good',
            "I'm not sure / I can't judge this",
          ],
          required: true,
          domain: 'learning_support',
        },
        {
          ordinal: 3,
          comparison_id: 'H3-DISP-003',
          display_title: 'Comparison 3 of 3',
          prompt: 'Rewrite this message politely: “I can\'t finish this today. I\'ll send it tomorrow.”',
          response_a: 'I won’t be able to complete this today, but I’ll send it to you tomorrow. Thanks for your patience.',
          response_b: 'I’m sorry, but I won’t be able to finish this today. I’ll send the completed version tomorrow. Thank you for understanding.',
          question: 'Which response would you rather receive?',
          choices: [
            'Response A is better',
            'Response B is better',
            'They are about equally good',
            'Neither response is good',
            "I'm not sure / I can't judge this",
          ],
          required: true,
          domain: 'writing',
        },
      ],
      reviewer_context: {
        enabled: true,
        title: 'Optional: Which best describes you?',
        choices: [
          'Student',
          'Teacher / educator',
          'Researcher / scientist / engineer',
          'Other working professional',
          'General user',
          'Prefer not to say',
        ],
        required: false,
      },
      optional_comment: {
        enabled: true,
        title: 'Optional: Anything else you want to tell us?',
        required: false,
      },
      confirmation_message: 'Thank you — your H3 pilot response has been recorded.',
      sandbox_auto_close_after_submissions: 3,
    },
    {
      form_packet_version: '1.1',
      protocol_version: '1.0',
      environment: 'sandbox',
      packet_id: 'HEF1-H3-B1-20260910',
      batch_id: 'HEB1-H3-UX-20260910',
      variant_id: 'B1',
      partition: 'development',
      reviewer_cohort: 'general_user',
      language: 'en',
      title: 'PAUL Open — H3 Durability Pilot — B1',
      description: 'Disposable non-research H3 pilot. Read each question and the two responses, then choose the response you would rather receive based on accuracy, clarity, usefulness and naturalness.',
      settings: {
        collect_email: false,
        allow_response_edits: false,
        limit_one_response_per_user: false,
        progress_bar: true,
        publish_response_summary: false,
        show_submit_another_response_link: false,
        shuffle_questions: false,
        accepting_responses: true,
      },
      comparisons: [
        {
          ordinal: 1,
          comparison_id: 'H3-DISP-001',
          display_title: 'Comparison 1 of 3',
          prompt: 'Why can a metal spoon feel colder than a wooden spoon even when both have been in the same room?',
          response_a: 'Metal naturally stays at a lower temperature than wood indoors because metal contains less stored heat. That lower temperature is what your hand detects.',
          response_b: 'They are usually at nearly the same room temperature. Metal conducts heat away from your hand much faster than wood, so your skin cools more quickly and the metal feels colder.',
          question: 'Which response would you rather receive?',
          choices: [
            'Response A is better',
            'Response B is better',
            'They are about equally good',
            'Neither response is good',
            "I'm not sure / I can't judge this",
          ],
          required: true,
          domain: 'general_science',
        },
        {
          ordinal: 2,
          comparison_id: 'H3-DISP-002',
          display_title: 'Comparison 2 of 3',
          prompt: 'I have 90 minutes before a quiz. How should I use the time?',
          response_a: 'Read the entire textbook chapter from the beginning so nothing is missed. If time remains, highlight the most important pages and reread them once.',
          response_b: 'Spend 10 minutes listing the topics and identifying your weakest two. Use 50 minutes for active recall and practice questions on those areas, 20 minutes to review mistakes, and the final 10 minutes for a quick summary and setup for the quiz.',
          question: 'Which response would you rather receive?',
          choices: [
            'Response A is better',
            'Response B is better',
            'They are about equally good',
            'Neither response is good',
            "I'm not sure / I can't judge this",
          ],
          required: true,
          domain: 'learning_support',
        },
        {
          ordinal: 3,
          comparison_id: 'H3-DISP-003',
          display_title: 'Comparison 3 of 3',
          prompt: 'Rewrite this message politely: “I can\'t finish this today. I\'ll send it tomorrow.”',
          response_a: 'I’m sorry, but I won’t be able to finish this today. I’ll send the completed version tomorrow. Thank you for understanding.',
          response_b: 'I won’t be able to complete this today, but I’ll send it to you tomorrow. Thanks for your patience.',
          question: 'Which response would you rather receive?',
          choices: [
            'Response A is better',
            'Response B is better',
            'They are about equally good',
            'Neither response is good',
            "I'm not sure / I can't judge this",
          ],
          required: true,
          domain: 'writing',
        },
      ],
      reviewer_context: {
        enabled: true,
        title: 'Optional: Which best describes you?',
        choices: [
          'Student',
          'Teacher / educator',
          'Researcher / scientist / engineer',
          'Other working professional',
          'General user',
          'Prefer not to say',
        ],
        required: false,
      },
      optional_comment: {
        enabled: true,
        title: 'Optional: Anything else you want to tell us?',
        required: false,
      },
      confirmation_message: 'Thank you — your H3 pilot response has been recorded.',
      sandbox_auto_close_after_submissions: 3,
    },
  ],
};
